cabal-version:      2.4
name:               eight-machina
version:            1.3
synopsis:           A CHIP-8 emulator thought in the functional paradigm and written in Haskell.
license:            MIT
license-file:       LICENSE
author:             Gonzalo Exequiel Ibars Ingman
build-type:         Simple
extra-doc-files:    README.md

executable 8-machina
  main-is:          Main.hs
  hs-source-dirs:   src
  other-modules:    Chip8.CPU
                  , Chip8.Fonts
                  , Chip8.Instruction
                  , Chip8.Interpreter
                  , Chip8.Keypad
                  , Chip8.Machine
                  , Chip8.Memory
                  , Chip8.Register
                  , Chip8.RegisterName
                  , Chip8.Stack
                  , Chip8.VideoMemory
                  , Graphics
                  , Keyboard
                  , Parser
                  , Sound
  build-depends:    base >=4.12 && <5
                  , bytestring
                  , containers
                  , optparse-applicative
                  , random >=1.2
                  , sdl2 >=2.5
                  , vector
  default-language: Haskell2010
  ghc-options:      -threaded
