cabal-version:      2.4
name:               eight-machina
version:            1.2
synopsis:           A CHIP-8 emulator thought in the functional paradigm and written in Haskell.
license:            MIT
license-file:       LICENSE
author:             Gonzalo Exequiel Ibars Ingman
build-type:         Simple
extra-doc-files:    README.md

executable 8-machina
  main-is:          Main.hs
  hs-source-dirs:   src
  other-modules:    CPU
                  , Fonts
                  , GameROMLoader
                  , Graphics
                  , Instruction
                  , Keyboard
                  , MachineState
                  , Memory
                  , Parser
                  , Quirks
                  , Register
                  , RegisterName
                  , Sound
                  , Stack
                  , VideoMemory
  build-depends:    base >=4.12 && <5
                  , array
                  , bytestring
                  , containers
                  , MonadRandom
                  , optparse-applicative
                  , process
                  , random
                  , sdl2 >=2.5
                  , split
                  , vector
  default-language: Haskell2010
  ghc-options:      -threaded
